### ISSUE TITLE
Grey screen on startup with version 1.0.3

### ISSUE THREAD

**Issue by canidorichard** [pavels/spektrum#11]
I downloaded and extracted the currently latest version 1.0.3 and extracted it in the root of C:\

When I execute spektrum.exe I just get a window with a grey background as reported for earlier versions.

I have installed the Visual C++ Redistributable for Visual Studio 2012 as requested and rebooted my PC

I am running Windows 10

Trying version 1.0.2 I get the same but with an error message stating that the application can not find rtl-sdr device.

Device is working fine with SDR#

**Comment by pavels** [comment]
32bit or 64bit windows?

**Comment by canidorichard** [comment]
64 bit

**Comment by pavels** [comment]
I found an error in binary release and fixed it. Pleas download the archive again and try again. It should work now.

**Comment by canidorichard** [comment]
Sadly this had made no difference at all

**Comment by pavels** [comment]
Unfortunately only way to debug this problem for you would be getting processing ide  from https://processing.org/ and library from https://github.com/pavels/processing-rtlspektum-lib/releases/download/1.0.5/rtlspektrum.zip and try to run it this way

You will get some console output in processing - that will give us some clues.

**Comment by canidorichard** [comment]
![image](https://user-images.githubusercontent.com/1258411/38044726-84a80a0e-32b2-11e8-98f0-df65b8bbe826.png)

Attached is what I get when launching the application.

To confirm I have installed the the Visual C++ Redistributable for Visual Studio 2012.

I can't see any logs from your application or anything written to the event logs that might shed some light.

Thanks for your help.

**Comment by artmaen** [comment]
I have same grey background with 1.0.3 updated version too. 1.0.2 working well (win7 64-bit).
When i replace rtlpower and rtlsdr.dll to older 1.0.2 versions, 1.0.3 starts working.

**Comment by canidorichard** [comment]
Following on from what @artmaen discovered I have also discovered I can get past the grey screen by just taking rtlsdr.dll from version 1.0.2.

After this I can get to the device selection screen which shows two devices but unfortunately it does not matter which I select, the application complains it can not connect to the device which is the same issue I get with version 1.0.2 only I don't see the device selection screen (which is new to 1.0.3) in that case.

**Comment by MovingMap** [comment]
Gentlemen,
I tried Version 1.0.3: With artmaen's hint it starts to do something, but it has nothing to do with the signals applied to the antenna port! The same happens with Version 1.0.2!
I'll try to include a screenshot of Version 1.0.2's output:
![spectrum_1_0_2](https://user-images.githubusercontent.com/35462244/38165693-b0a322c6-3517-11e8-8054-a58881b0f51b.JPG)
Does anybody else have this behaviour? I tried a second RTLSDR-Stick but with same result. Both are RTL2832U T820T2 TCXU+BIAS T+HF V.3
As gain, I only can choose "0".
Win7 64bit...
Thanks in advance

Edit: 
Ok, my fault - I didn't know I have to run zadig.exe in order to replace the automatically installed driver (see http://rtlsdr.org/softwarewindows for details).

Best regards

**Comment by Deiran** [comment]
I have the same problem with spektrum. When I run the application version 1.0.3 only the gray background appears and nothing else.  I run the application on Windows 10 x64 with RTL2832U + R820T2 USB dongle. At the same time, the old version of the application (version 1.0.2) is started and works normally.
![spektrum](https://user-images.githubusercontent.com/38084922/38333142-66bc0a8c-3860-11e8-82fd-cfe9b95c00ed.JPG)

**Comment by iotlearner0level** [comment]
I opened the program inside processing. here is what i get (windows 10/64bit)


Loading libs from C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library.
Library rtlsdr file C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll.
Library rtlpower file C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlpower.dll.
# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\processing.app.SketchException: UnsatisfiedLinkError: rtlspektrum.RtlsdrLibrary.rtlsdr_get_device_count()I
	at processing.mode.java.JavaBuild.placeException(JavaBuild.java:650)
	at processing.mode.java.runner.Runner.findException(Runner.java:814)
	at processing.mode.java.runner.Runner.reportException(Runner.java:789)
	at processing.mode.java.runner.Runner.exceptionEvent(Runner.java:709)
	at processing.mode.java.runner.Runner$2.run(Runner.java:599)
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.

**Comment by iotlearner0level** [comment]
sorry but i haven't used processing until now. looks like arduino to me but for  Java :)
there is some mention of loading certain module from the rtlsdr library. and there is something about 32-bit...
	at rtlspektrum.RtlsdrLibrary.rtlsdr_get_device_count(Native Method)
	at rtlspektrum.Rtlspektrum.getDevices(Rtlspektrum.java:64)
	at spektrum.setup(spektrum.java:418)
	at processing.core.PApplet.handleDraw(PApplet.java:2401)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1557)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)

relevant lines are:
Rtlspektrum.java:64
   int deviceCount = RtlsdrLibrary.rtlsdr_get_device_count();
spektrum.java:418
  devices = Rtlspektrum.getDevices();

error occurs when a call is made to get device count and getdevices from the rtlsdr.dll library which it says is 
# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.

however, first few lines say, it has found the these dlls:
Loading libs from C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library.
Library rtlsdr file C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll.
Library rtlpower file C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlpower.dll.
=====================

so what could be wrong?

If you can guide me step by step, maybe this problem could be resolved. i can't solve it myself because
a) i don't know java
b) spektrum is a complicated program i don't understand
c) don't understand how rtlsdr.dll works
d) my skills are pretty limited


however, i need a "poor man's" spectrum analyser...so

**Comment by pavels** [comment]
Hi

thanks for the feedback - there is clearly something messed up with the rtlsdr binaries bundled with 1.0.3 i will try to sort it out today or during the weekend

@iotlearner0level try to copy dlls from here https://github.com/pavels/processing-rtlspektum-lib/releases/download/1.0.3/rtlspektrum.zip and replace the ones in the library and try again please

**Comment by iotlearner0level** [comment]
I replaced all the contents of documents>processing>libraries>rtlspektrum

Now the error message shows function getDevices() doesn not exist!


processing.app.SketchException: The function getDevices() does not exist.
	at processing.mode.java.JavaBuild.placeException(JavaBuild.java:650)
	at processing.mode.java.Compiler.compile(Compiler.java:162)
	at processing.mode.java.JavaBuild.build(JavaBuild.java:128)
	at processing.mode.java.JavaBuild.build(JavaBuild.java:106)
	at processing.mode.java.Debugger.startDebug(Debugger.java:189)
	at processing.mode.java.Debugger.step(Debugger.java:278)
	at processing.mode.java.Debugger.stepOver(Debugger.java:296)
	at processing.mode.java.JavaEditor.handleStep(JavaEditor.java:1149)
	at processing.mode.java.JavaToolbar$2.actionPerformed(JavaToolbar.java:82)
	at processing.app.ui.EditorButton.mousePressed(EditorButton.java:189)
	at java.awt.Component.processMouseEvent(Component.java:6530)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by pavels** [comment]
@iotlearner0level yes - you need to replace only dlls, not jar files

**Comment by iotlearner0level** [comment]
grey windows with the following errors:

Loading libs from C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library.
Library rtlsdr file C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll.
Library rtlpower file C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlpower.dll.
# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\library\rtlsdr.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\XYZ\Documents\Processing\libraries\rtlspektrum\processing.app.SketchException: UnsatisfiedLinkError: rtlspektrum.RtlsdrLibrary.rtlsdr_get_device_count()I
	at processing.mode.java.JavaBuild.placeException(JavaBuild.java:650)
	at processing.mode.java.runner.Runner.findException(Runner.java:814)
	at processing.mode.java.runner.Runner.reportException(Runner.java:789)
	at processing.mode.java.runner.Runner.exceptionEvent(Runner.java:709)
	at processing.mode.java.runner.Runner$2.run(Runner.java:599)
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.

**Comment by wgaylord** [comment]
Any progress?

**Comment by iotlearner0level** [comment]
I don't know if this thread is active or not but i downloaded the 1.0.3 release from the releases page and unzipped to f:/>software>spektrum and run the .exe as adminsitrator and it works!!!!

**Comment by eukaio** [comment]
> unfortunately it does not matter which I select, the application complains it can not connect to the device which i

Any progress? I have the same situation

**Comment by BrianD2019** [comment]
I too am getting the same gray screen. I read above where rtlpower.dll and rtlsdr.dll were swapped out for the 2015 version and it worked. It seems the 2018 version is of the two .dll files do not like my machines (I tried on three different computers). With the older version of the .dll I do not know what I am missing since I cannot run the 2018 version. Is there anyway to test why the 2015 works but the  2018 does not work? Thanks in advance, and I really like this program. Wish it had equivalent RBW and VBW.

**Comment by wadoadi** [comment]
Same issue here!

**Comment by BrianD2019** [comment]
Wadoadi, I went with Spektrum 0.19a instead of 1.0.3. I found it to have a better UI and it works. I don't recall if I had to do some magic to get it to work. I don't think so. However, there is a bug on Windows 10 that multiple SDR dongles might appear. When that happens all bets are off that it will work. I use it on my Windows 7 and 8 machines and have no problems. Why on Windows 10 it does not work for me I don't know.

Anyway, try Spektrum 0.19a.

**Comment by wadoadi** [comment]
Thanks Brian, I have tried this and also 0.11 and I just get the grey screen on Windows 10, also tried compatibility mode, I no longer have a W7 PC, I can't remember the version I used to run on that PC but it did work on it.

**Comment by pavels** [comment]
Hi

I have release new version just now - 1.0.4 - get if from releases https://github.com/pavels/spektrum/releases/tag/1.0.4

This should finally sort out this problem on linux and windows.

Pleas test and let me know here in this issue if it fixed the problem or not.

**Comment by jpooley-hearst** [comment]
This update seems to fix the issue for me on Windows, thanks!

**Comment by BrianD2019** [comment]
I loaded the new version. It works. I have removed version 0.19a. Both versions work on my Win8 machine. I like the multipage layout and controls of version 0.19a, but I also like the simple layout of version 1.04. I just wish the layout and controls were more like an HP/Agilent/Schwarz interface. However, thanks for the fix.

 

Brian D

KF6BL

**Comment by chaos511** [comment]
That update fixed it for me

**Comment by wadoadi** [comment]
Fixed for me too! Fantastic thank you @pavels 

Would it be possible to ask for the use of frequency suffixes in the range boxes i.e 800MHz or 1Ghz instead of always entering in Hz?

**Comment by BrianD2019** [comment]
I think the sweep button is not working correctly. I see that there is a sweep in progress, but there is visual indication, meaning, the vertical cursor is not sweeping like in Version 0.19a. Maybe it is my machine, but I don’t see an indication that a sweep is being performed. But just let me say that I know it is happening, button or no button.

**Comment by TiberiusJ** [comment]
Hi Pavels,
It now works a treat on W10 x64 (Parallels Desktop - MacBook Pro Mid i5 2012 2TB SSD 16GB Ram)
A little messing around getting the USB SDR Dongle to be addressed in W10 VM, forced driver with Zadig.
Thanks! Dave G7UAY

**Comment by pavels** [comment]
Ok, so who liked 0.19a - good news - it is now IN - so get version 2.0.0

If there is more problems with grey screen, please open new issu, i am closing this for now as it looks like it is solved.

About the "use of frequency suffixes" - its is planned, please open separate issue
