### ISSUE TITLE
Max hold function is bizarre

### ISSUE THREAD

**Issue by patchvonbraun** [pavels/spektrum#13]
The max-hold function appears to not have any "memory", so it doesn't work the way you'd naturally expect such a function to work, where it simply keeps bumping up the "max" until reset.  This implementation seems to have a very short "memory".

If there's some justification for such a behavior, it would be nice to be able to get the "usual"
  behavior for "max/min hold".

**Comment by pavels** [comment]
The SV mod is merged in and version 2.0.0 released - New MIN/MAX hold is in
