### ISSUE TITLE
dB unit

### ISSUE THREAD

**Issue by Leonix2007** [pavels/spektrum#14]
Hi there,

Great job for the contribution for this analyzer.  

Related to the Y-axis which is in the dB unit. dB is a relative measure not an absolute value.  Can you please verify if it is in dBm, dBi or maybe dBd?

Thanks,
Leonix2007

**Comment by pavels** [comment]
It measures power - it displays values as it gets them from the dongle itself - no calibration

You can theoretically feed it 1mW flat white noise and use relative function to zero it to known reference - otherwise i think the reference is some arbitrary value.
