### ISSUE TITLE
Spektrum additions help

### ISSUE THREAD

**Issue by TiberiusJ** [pavels/spektrum#15]
Dear Pavel, thank you for this great software. I would like to help with development and learn in the process. What I would like to do is:
Be able to store scans to database (text file etc) so they can be replayed offline later.
Be able to write a schedule of scans, eg. Scans with differing resolutions for different bands.
For example:
Job 1: Scan 70-88Mhz 20 times
Job 2: Scan 110-136 Mhz 10 times
Job 3: Scan 136-200 Mhz 10 times
Job 4: Scan 200-400 Mhz 5 times
Job 5: Scan 400-500 Mhz 20 times
Job 6: Scan 500-800 Mhz 2 times
Repeat

Then run all jobs in order and store scan points in a file so they can be replayed later.
Next, using data in the text file, construct a library of signals that for example 20dB above the noise. Then be able to annotate the library of known signals.
Next auto add unknown signals to another file for later analysis but have the option to scan and ignore known signals.
Like a glorified scanner with better library management. I have reviewed many of the plugins for the Airspy but I prefer Spektrum because of the span stitching.

If I can learn how to do this, I will be very happy to contribute.

**Comment by pavels** [comment]
Hi

spektrum is more of a graphical tool - it aims to "emulate" spectrum analyzer.

What you actually need is Rtl Power - http://kmkeen.com/rtl-power/ - it is a command line tool which does exactly what you want - combined with some scripting you should be able to achieve what you want pretty easy.
