### ISSUE TITLE
Spektrum in Ubuntu 19.04

### ISSUE THREAD

**Issue by kc8sbv** [pavels/spektrum#19]
I got Spektrum to launch, and I need to enter my tuning offset, but the interface doesn't look like the pictures, there doesn't seem to be a window to enter my offset value. Can you help?

**Comment by pavels** [comment]
How does your interface look like? Also i think offset is not supported

**Comment by kc8sbv** [comment]
will try it again, not using 19.04 anymore. I hope you can add the necessary windows to allow frequency offset... So I can use this to be able to tune down to HF frequencies

 https://airspy.com/spyverter-r2

**Comment by pavels** [comment]
The SV mod is merged in and version 2.0.0 released - it has the offset feature
