### ISSUE TITLE
support HackRF

### ISSUE THREAD

**Issue by Aksonx2** [pavels/spektrum#22]
Good afternoon to everyone!
What do I need to do to ensure that the program supports HackRF?
Thanks.

**Comment by pavels** [comment]
This project is based on https://osmocom.org/projects/rtl-sdr/wiki/Rtl-sdr - works with cheap Realtek RTL2832U dongles

It would be a lot of work to make it work with HackRF. If somebody wants to contribute, than why not, create Pull Request. It is doable, but without the hardware it is very hard / impossible.
