### ISSUE TITLE
Grey Screen even with VS 2012 Installed

### ISSUE THREAD

**Issue by jpooley-hearst** [pavels/spektrum#23]
Hi, 

I am getting the gray screen when opening Spektrum on a newly imaged 1903 Windows computer. I have received a signal in SDR# just fine before attempting to setup Spektrum. 

Both Visual Studio 2012 x86 and x64 are installed. I have also tried with just x64. 

Please let me know if you have any suggestions as to how to resolve this issue. Thanks!

**Comment by ArielBaravalle** [comment]
same problem.

**Comment by pavels** [comment]
Lets discuss here #11
