### ISSUE TITLE
Request: Ability to set known device error (say in PPM)? 

### ISSUE THREAD

**Issue by TheOriginalFreddoFrog** [pavels/spektrum#25]
Is it possible to add as an enhancement at the setup phase a known PPM or fixed frequency error correction value? 

and/or for future down the line ... 

Is it possible to load/develop an end user-adjustable table of known corrections that can be applied across the device spectrum range at runtime?

**Comment by pavels** [comment]
This can be achieved using `IF frequency` setting which can work as sort of correction
