### ISSUE TITLE
spektrum installation location

### ISSUE THREAD

**Issue by Allasso** [pavels/spektrum#28]
Please forgive if I am just having brain fog, also Windows is my third language.  Also please forgive that I didn't pay close attention when installing.

I Installed spektrum on Windows 8, app started up after the install.  After closing it I went to find it in 'Program Files' and 'Program Files (x86)' in order to place it on my task bar and create shortcut.  But I find no folders that resemble something like 'spektrum' or 'pavels'.  I checked my Desktop for a similar named shortcut but found none.

Please tell me the installation location so I can find it and put it on my task bar.

Thanks! Kevin Jones

**Comment by pavels** [comment]
Hi

this thing has no installer at all - you download the .zip file and extract it somewhere (right click - extract here - there will appear new folder right next to the zip file) - than you just run the exe file in the folder

if you want link - extract the zip for example to your documents folder, than run zip, right click on it on the bottom bar and choose "pin"
