### ISSUE TITLE
Operation

### ISSUE THREAD

**Issue by Allasso** [pavels/spektrum#31]
A couple of questions re operation:

Does the screen update in sync with the generator sweep rate?  (takes ~ 2 seconds to sweep from 700 to 1000 MHz)

Can the sweep rate be increased?

What is the dB scale relative too?  More importantly, is there a way to set scale to read dBM present at the input of the SDR?  And if not, can one compute the dBm present at the input of the SDR?  (Like, can you read the scale dB values, subtract the gain settings, and arrive at this?  Or something like that?)

**Comment by pavels** [comment]
1) The sweep is not synchronized to anything - to take measurements with signal source (for antennas or filters) you need wide band noise source (like the BG7TBL noise source).

2) The sweep speed is limited to how fast the tuner in the dongle can tune and stabilize - these kinds of tuners are not really designed for fast tuning - you normally tune it to single channel and watch TV on that channel. So unfortunately i can't make it any faster

3) This was designed to work with various cheap DVB-T dongles. These are most likely not calibrated in any way - so there is probably no useful way to determine absolute signal level as-is. The software has so called "relative mode" - that means if you first feed it some known signal it will record that and than will subtract this from the measured signal (you will establish your known 0 - the dB value will be than relative to this signal) - this way if for example your noise source is not perfectly linear, it can take this into account. See https://github.com/pavels/spektrum#relative-mode
