### ISSUE TITLE
Remote dongle possible ?

### ISSUE THREAD

**Issue by hanslammerts** [pavels/spektrum#32]
Will it be possible to have spektrum running on one Linux machine (graphical machine) and have it connect to an RTL-SDR dongle that is connected to another Linux machine, e.g. by using rtl_tcp ?

Thanks,
Hans

**Comment by pavels** [comment]
rtl_tcp won't work in this case

But check http://usbip.sourceforge.net/ - it should be able to connect any USB device over IP
