### ISSUE TITLE
rtlspektrum-lib: Jar file missing

### ISSUE THREAD

**Issue by pmbdk** [pavels/spektrum#33]
It seems that the jar-file in all releases of processing-rtlspektrum-lib is missing. Being a total noob within processingg, do I need to re-create it somehow before adding is to the processing sketchbook?

**Comment by pavels** [comment]
When i moved towards automated build i removed that as it was outdated and i was kind of lazy to automate that build - the .jar as well as .dll / .so file are in `lib` directory of the main release https://github.com/pavels/spektrum/releases

So as it is now you need to get the source of the  processing-rtlspektrum-lib, put it in the processing `libraries` directory a name it `rtlspektrum` and than get following binaries from main release:

```
bridj.jar
librtlpower.so
librtlsdr.so
rtlspektrum.jar
```
(substitute .so for .dll if you are on windows)

and put them in `library` folder inside `rtlspektrum` folder

end result looking like this (in the processing `libraries` dir):
```
rtlspektrum
├── library
│   ├── bridj.jar
│   ├── librtlpower.so
│   ├── librtlsdr.so
│   └── rtlspektrum.jar
└── library.properties
```

I should probably move this info to README
